#!/usr/bin/env python3
"""Subset the installed LVGL Montserrat bitmaps; no new font dependency.

Keep digit advances equal so values do not jitter. Rate digits are permanently
75% wide, at the same 42px height; the clock keeps the original proportions.
Run after PlatformIO has installed lv_arduino, then commit DisplayFonts.c.
"""
from pathlib import Path
import math
import re

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / ".pio/libdeps/nodemcuv2/lv_arduino/src/src/lv_font"


def source_font(size):
    source = (FONTS / f"lv_font_montserrat_{size}.c").read_text()
    bitmap = source.split("gylph_bitmap[] =", 1)[1].split("};", 1)[0]
    bitmap = re.sub(r"/\*.*?\*/", "", bitmap, flags=re.S)
    bitmap = [int(n, 0) for n in re.findall(r"0x[0-9a-f]+|\d+", bitmap)]
    descriptors = source.split("glyph_dsc[] =", 1)[1].split("};", 1)[0]
    glyphs = [dict((key, int(value)) for key, value in re.findall(r"\.(\w+) = (-?\d+)", row))
              for row in re.findall(r"\{([^}]+)\}", descriptors)]
    return bitmap, glyphs


def make_font(name, size, characters, digit_width, horizontal=1):
    bitmap, source = source_font(size)
    data, glyphs = [], [dict(bitmap_index=0, adv_w=0, box_w=0, box_h=0, ofs_x=0, ofs_y=0)]
    for character in sorted(set(characters)):
        original = source[ord(character) - 31]
        width, height = original["box_w"], original["box_h"]
        pixels = [(bitmap[original["bitmap_index"] + i // 2] >> (4 if i % 2 == 0 else 0)) & 15
                  for i in range(width * height)]
        scaled_width = math.ceil(width * horizontal)
        # Area averaging preserves narrow strokes in the permanently condensed font.
        scaled = []
        for y in range(height):
            for x in range(scaled_width):
                start, end = x * width / scaled_width, (x + 1) * width / scaled_width
                value = sum(pixels[y * width + k] * max(0, min(end, k + 1) - max(start, k))
                            for k in range(math.floor(start), math.ceil(end))) / (end - start)
                scaled.append(round(value))
        advance = digit_width if character.isdigit() else round(original["adv_w"] / 16 * horizontal)
        glyph = dict(bitmap_index=len(data), adv_w=advance * 16, box_w=scaled_width,
                     box_h=height, ofs_x=max(0, (advance - scaled_width) // 2), ofs_y=original["ofs_y"])
        glyphs.append(glyph)
        if len(scaled) % 2:
            scaled.append(0)
        data.extend((scaled[i] << 4) | scaled[i + 1] for i in range(0, len(scaled), 2))

    bitmap_text = "\n".join("    " + ", ".join(f"0x{v:02x}" for v in data[i:i+16]) + ","
                            for i in range(0, len(data), 16))
    descriptors = "\n".join("    {" + ", ".join(f".{k} = {v}" for k, v in g.items()) + "}," for g in glyphs)
    unicodes = ", ".join(str(ord(c) - 32) for c in sorted(set(characters)))
    return f'''
static LV_ATTRIBUTE_LARGE_CONST const uint8_t {name}_bitmap[] = {{
{bitmap_text}
}};
static const lv_font_fmt_txt_glyph_dsc_t {name}_glyphs[] = {{
{descriptors}
}};
static const uint16_t {name}_unicode[] = {{{unicodes}}};
static const lv_font_fmt_txt_cmap_t {name}_map[] = {{{{
    .range_start = 32, .range_length = 95, .glyph_id_start = 1,
    .unicode_list = {name}_unicode, .glyph_id_ofs_list = NULL,
    .list_length = {len(glyphs)-1}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
}}}};
static lv_font_fmt_txt_dsc_t {name}_data = {{
    .glyph_bitmap = {name}_bitmap, .glyph_dsc = {name}_glyphs,
    .cmaps = {name}_map, .kern_dsc = NULL, .kern_scale = 0,
    .cmap_num = 1, .bpp = 4, .kern_classes = 0, .bitmap_format = 0
}};
lv_font_t {name} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {46 if size == 42 else 24}, .base_line = {8 if size == 42 else 4},
    .subpx = LV_FONT_SUBPX_NONE, .dsc = &{name}_data
}};
'''


if __name__ == "__main__":
    content = '/* Generated by scripts/generate_fonts.py from LVGL Montserrat-Medium. */\n#include <lvgl.h>\n'
    content += make_font("monitor_clock_42", 42, "0123456789:-", 28)
    content += make_font("monitor_rate_42", 42, "0123456789.-", 21, .75)
    content += make_font("monitor_value_22", 22, "0123456789.-+%BKMGTP", 15)
    content += make_font("monitor_metric_22", 22, "0123456789.-%", 11, .75)
    (ROOT / "src/DisplayFonts.c").write_text(content)
    print("Generated four fixed digit subsets in src/DisplayFonts.c")
